# Generated by Django 6.0.6 on 2026-06-27 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='proof_type',
            field=models.CharField(choices=[('none', 'No Proof'), ('cash', 'Paid in Cash'), ('image', 'Payment Screenshot')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('proof_type', models.CharField(choices=[('none', 'No Proof'), ('cash', 'Paid in Cash'), ('image', 'Payment Screenshot')], default='none', max_length=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='settlement_proofs/')),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='core.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='core.group')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='core.member')),
            ],
        ),
    ]
