# Generated by Django 6.0.6 on 2026-06-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_proof_image_expense_proof_type_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('proof_type', models.CharField(choices=[('none', 'No Proof'), ('cash', 'Paid in Cash'), ('image', 'Payment Screenshot')], default='none', max_length=10)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='iou_proofs/')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ious_taken', to='core.member')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ious', to='core.group')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ious_given', to='core.member')),
            ],
        ),
    ]
