# Generated by Django 6.0.6 on 2026-08-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_iou'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='delete_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
